### ISSUE TITLE
Make it easy for members to get in touch about bugs and issues with their data

### ISSUE THREAD

**Issue by erkannt** [Makespace/members-app#76]

**Comment by Lan2u** [comment]
Does anyone have any ideas about how best to do this?

Could do something completely in-app (ticketting system), might end up being quite a bit to maintain though.

Could just have a mailto: button and then have it send an email to a makespace account we all have access to?
- Could have a button that sends the email through the app with extra diagnostic information attached (rather than needing to rely on users writing sufficiently detailed bug reports)

**Comment by erkannt** [comment]
I'd say keep it simple for now and evolve. Mailto link with prepopulated subject and maybe even body.

How about a nice big button in the nav bar that takes you to a 'report issues' page. Then we have space to evolve things and give people a little bit of context before the link dumps them into their mail program.

**Comment by erkannt** [comment]
There are three google group email addresses (db team, it-maintainers, infosystems). We could potentially re-use one of those or I can create a new one e.g. app-support@makespace.org
